# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('marks', models.CharField(max_length=120)),
                ('userid', models.CharField(max_length=120)),
            ],
        ),
    ]
