# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convert_from', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('SGB', 'SGB'), ('BGN', 'BGN'), ('ILS', 'ILS'), ('AED', 'AED'), ('HKD', 'HKD'), ('SGD', 'SGD')], default='INR', max_length=3)),
                ('convert_to', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('SGB', 'SGB'), ('BGN', 'BGN'), ('ILS', 'ILS'), ('AED', 'AED'), ('HKD', 'HKD'), ('SGD', 'SGD')], default='USD', max_length=3)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=120)),
            ],
        ),
    ]
