# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=120, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('qualification', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
