# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app2', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=120)),
                ('apply_job', models.ManyToManyField(to='my_app2.Job')),
            ],
        ),
    ]
