# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app2', '0003_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='userid',
            field=models.IntegerField(max_length=120),
        ),
    ]
