# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app2', '0004_auto_20180708_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
