# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app2', '0005_auto_20180708_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='userid',
            field=models.IntegerField(unique=True),
        ),
    ]
