# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app2', '0006_auto_20180708_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
